name: audio_player
description: An App that will play any audio file.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  permission_handler: ^10.2.0
  on_audio_query: ^2.6.2
  just_audio: ^0.9.31
  audio_video_progress_bar: ^1.0.0
  on_audio_room: ^2.2.1+1
  intl: ^0.18.0
  audio_service: ^0.18.9



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - images/call_recorder_logo.png
    - images/musical_notes.png
    - images/music_music.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700